name: Converter Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4      
       
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --detectOpenHandles --forceExit

      - name: Deploy to VPS
        run: |
          # Install sshpass for password authentication
          sudo apt-get update && sudo apt-get install -y sshpass
         
          # Test SSH connection first
          sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 root@185.98.138.207 'echo "SSH connection successful"'
         

          # Create directory on VPS if it doesn't exist
          sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 root@185.98.138.207 'mkdir -p /var/www/convert-api'
         
          # Copy production files to VPS
          sshpass -p "${{ secrets.PASSWORD }}" scp -o StrictHostKeyChecking=no -o ConnectTimeout=30 -r convert.js package.json index.html root@185.98.138.207:/var/www/convert-api/
         

          # Install dependencies, install PM2 globally, and start service
          sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 root@185.98.138.207 'cd /var/www/convert-api && npm install --production && npm install -g pm2 && pm2 restart convert-api || pm2 start convert.js --name convert-api'
